version: '3'
services:
  rtvis:
    container_name: rtvis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    volumes:
      - .:/rtvis
    command: python -u app.py
# if you want to use a static IP address inside the docker (possibly useful for connecting to a database or reverse proxy), ), uncomment the following lines
    # networks:
    #   rtvis_net:
    #     ipv4_address: 173.26.0.2

# networks:
#   rtvis_net:
#     external: true